services:
  api:
    build:
      dockerfile: packages/api/Dockerfile
    volumes:
      - ${MUSIC_LIBRARY_PATH}:/musiclibrary
    networks:
      - api
    environment:
      - MUSIC_LIBRARY_PATH=/musiclibrary
  web:
    build:
      dockerfile: packages/web/Dockerfile
    ports:
      - "80:80"
    networks:
      - web
      - api
    depends_on:
      - api
    restart: "on-failure"

networks:
  web:
  api:
