[project]
name = "megawave"
version = "0.0.1"
description = "Self hosted music streaming api"
authors = [{ name = "Anthony Powell", email = "powell.anthonyd@proton.me" }]
license = "MIT"
requires-python = ">=3.12"
dependencies = [
  "mutagen>=1.47.0",
  "fastapi[standard]>=0.115.8",
  "uvicorn>=0.34.0",
  "aiofiles>=24.1.0",
]

[project.optional-dependencies]
dev = ["mypy>=1.8.0", "ruff>=0.2.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
fix = true

[tool.ruff.lint.isort]
known-first-party = ["megawave"]

[tool.mypy]
files = ["megawave"]
ignore_missing_imports = true
