[tool.poetry]
name = "megawave"
version = "0.0.1"
description = "Self hosted music streaming api"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
mutagen = "^1.47.0"
fastapi = "^0.107.0"
uvicorn = "^0.25.0"
aiofiles = "^23.2.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
fix = true

[tool.ruff.lint.isort]