[project]
name = "megawave"
version = "0.0.1"
description = "Self hosted music streaming api"
authors = [{ name = "Anthony Powell", email = "powell.anthonyd@proton.me" }]
license = "MIT"
requires-python = ">=3.12"
dependencies = [
  "mutagen>=1.47.0",
  "fastapi>=0.115.8",
  "uvicorn>=0.34.0",
  "aiofiles>=24.1.0",
]

[project.optional-dependencies]
dev = ["mypy>=1.8.0", "pytest>=7.4.4", "pytest-cov>=4.1.0", "ruff>=0.2.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
fix = true

[tool.ruff.lint.isort]
known-first-party = ["megawave"]

[tool.mypy]
files = ["megawave", "test"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.coverage.run]
source = ["megawave"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if self\\.debug",
  "raise AssertionError",
  "raise NotImplementedError",
  "if 0:",
  "if __name__ == .__main__.:",
]
