[tool.poetry]
name = "megawave"
version = "0.0.1"
description = "Self hosted music streaming api"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
mutagen = "^1.45.1"
fastapi = "^0.68.0"
uvicorn = "^0.14.0"
aiofiles = "^0.7.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"
isort = "^5.6.4"
flake8 = "^3.8.4"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"